/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe.Administrador.Empleados;

import Catalogos.Personal.Empleado;
import Jframe.Administrador.Catalogos;
import java.io.*; 
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author manri
 */
public class CatalogoEmpleado extends javax.swing.JFrame {
    ArrayList<Empleado> listaEmpleados = new ArrayList<>();
    /** 
     * Creates new form Empleadoss
     */
    public CatalogoEmpleado() {
        initComponents();
        cargarDesdeArchivo();
    }

    
    public void setListaEmpleados(ArrayList<Empleado> listaEmpleados) {
        this.listaEmpleados = listaEmpleados;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefonoEmpleado = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        emailEmpleado = new javax.swing.JTextField();
        labelEmaill = new javax.swing.JLabel();
        registrarEmpleado = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        apellidosEmpleado = new javax.swing.JTextField();
        labelApellidos = new javax.swing.JLabel();
        cuidadEmpleado = new javax.swing.JTextField();
        labelCuidad = new javax.swing.JLabel();
        direccionEmpleado = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        volverACatalogo = new javax.swing.JButton();
        labelTelefono1 = new javax.swing.JLabel();
        editarEmpleado = new javax.swing.JButton();
        labelTelefono3 = new javax.swing.JLabel();
        labelTelefono4 = new javax.swing.JLabel();
        limpiarEspacios = new javax.swing.JButton();
        labelTelefono5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoEmpleadoActionPerformed(evt);
            }
        });

        labelTelefono.setText("Teléfono");

        emailEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEmpleadoActionPerformed(evt);
            }
        });

        labelEmaill.setText("Correo Electronico");

        registrarEmpleado.setText("Registrar Empleado");
        registrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpleadoActionPerformed(evt);
            }
        });

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre");

        apellidosEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosEmpleadoActionPerformed(evt);
            }
        });

        labelApellidos.setText("Apellidos");

        cuidadEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuidadEmpleadoActionPerformed(evt);
            }
        });

        labelCuidad.setText("Cuidad");

        direccionEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionEmpleadoActionPerformed(evt);
            }
        });

        labelDireccion.setText("Dirección");

        volverACatalogo.setText("Volver a Catalogo");
        volverACatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverACatalogoActionPerformed(evt);
            }
        });

        labelTelefono1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelTelefono1.setText("Editar e Inactivar Empleado");

        editarEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        editarEmpleado.setText("Editar");
        editarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoActionPerformed(evt);
            }
        });

        labelTelefono3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelTelefono3.setText("Agregar Nuevo Empleado");

        labelTelefono4.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        labelTelefono4.setText("Catalogo Empleado");

        limpiarEspacios.setText("Limpiar");
        limpiarEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarEspaciosActionPerformed(evt);
            }
        });

        labelTelefono5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelTelefono5.setText("->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre)
                                    .addComponent(cuidadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCuidad)
                                    .addComponent(labelTelefono)
                                    .addComponent(telefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(registrarEmpleado)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelApellidos)
                                    .addComponent(apellidosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDireccion)
                                    .addComponent(direccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmaill)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(limpiarEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTelefono3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTelefono4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                                .addComponent(volverACatalogo))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTelefono1)
                        .addGap(18, 18, 18)
                        .addComponent(labelTelefono5)
                        .addGap(18, 18, 18)
                        .addComponent(editarEmpleado)
                        .addGap(222, 222, 222)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono4)
                    .addComponent(volverACatalogo))
                .addGap(41, 41, 41)
                .addComponent(labelTelefono3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuidad)
                    .addComponent(labelDireccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuidadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(labelEmaill))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarEmpleado)
                    .addComponent(limpiarEspacios))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarEmpleado)
                    .addComponent(labelTelefono1)
                    .addComponent(labelTelefono5))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEmpleadoActionPerformed

    private void emailEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEmpleadoActionPerformed
    public void agregarEmpleado(Empleado empleado){
        listaEmpleados.add(empleado);  
    }
    private void registrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpleadoActionPerformed
        try {
        cargarDesdeArchivo();

        String nombreEmpleado = nombre.getText();
        String apellidos = apellidosEmpleado.getText();
        String ciudad = cuidadEmpleado.getText();
        String direccion = direccionEmpleado.getText();
        String telefono = telefonoEmpleado.getText();
        String email = emailEmpleado.getText();
        boolean estado = true;

        if (nombreEmpleado.isEmpty() || apellidos.isEmpty() || ciudad.isEmpty() || direccion.isEmpty()
                || telefono.isEmpty() || email.isEmpty()) {
            throw new Exception("Algunos de los campos requeridos no fueron completados");
        } else {
            Empleado existente = encontrarEmpleado(nombreEmpleado,email);
            if (existente != null) {
                JOptionPane.showMessageDialog(null, "El empleado ya existe!");
            } else {
                // El empleado no existe, agrégalo
                Empleado empleado = new Empleado();
                empleado.setNombre(nombreEmpleado);
                empleado.setApellidos(apellidos);
                empleado.setCuidad(ciudad);
                empleado.setDirrecion(direccion);
                empleado.setTelefono(telefono);
                empleado.setEmail(email);
                empleado.setEstado(true);

                listaEmpleados.add(empleado);
                guardarEnArchivo();
                JOptionPane.showMessageDialog(null, "Empleado Correctamente Agregado");
                limpiar();
                
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al agregar los datos: " + e.getMessage(), "Error!",
                JOptionPane.INFORMATION_MESSAGE);
    }
        
    
    }//GEN-LAST:event_registrarEmpleadoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidosEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosEmpleadoActionPerformed

    private void cuidadEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuidadEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuidadEmpleadoActionPerformed

    private void direccionEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionEmpleadoActionPerformed

    private void volverACatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverACatalogoActionPerformed
        Catalogos catalogos = new Catalogos();
        catalogos.setVisible(true);
        catalogos.pack();
        catalogos.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volverACatalogoActionPerformed

    private void editarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoActionPerformed
        cargarDesdeArchivo();
        String nombreEmpleado = JOptionPane.showInputDialog("Nombre Empleado");
        String emailEmpleado = JOptionPane.showInputDialog("Correo Electronico Empleado:");

    Empleado empleado = encontrarEmpleado(nombreEmpleado, emailEmpleado);

    if (empleado != null) {
        mostrarEmpleadoEspecifico(empleado);

        editarNombre(empleado);
        editarApellidos(empleado);
        editarCiudad(empleado);
        editarDireccion(empleado);
        editarTelefono(empleado);
        editarEmail(empleado);
        editarEstado(empleado);

        
        guardarEnArchivo();
    } else {
        JOptionPane.showMessageDialog(null, "Empleado no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    private void editarNombre(Empleado empleado) {
        String nuevoNombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre del empleado (o presione OK si no quiere cambiarlo)");
        if (!nuevoNombre.isEmpty()) {
            empleado.setNombre(nuevoNombre);
        }
    }

    private void editarApellidos(Empleado empleado) {
        String nuevosApellidos = JOptionPane.showInputDialog("Ingrese los nuevos apellidos del empleado (o presione OK si no quiere cambiarlos)");
        if (!nuevosApellidos.isEmpty()) {
            empleado.setApellidos(nuevosApellidos);
        }
    }

    private void editarCiudad(Empleado empleado) {
        String nuevaCiudad = JOptionPane.showInputDialog("Ingrese la nueva cuidad del empleado (o presione OK si no quiere cambiarla)");
        if (!nuevaCiudad.isEmpty()) {
            empleado.setCuidad(nuevaCiudad);
        }
    }

    private void editarDireccion(Empleado empleado) {
        String nuevaDireccion = JOptionPane.showInputDialog("Ingrese la nueva direccion del empleado (o presione OK si no quiere cambiarla)");
        if (!nuevaDireccion.isEmpty()) {
            empleado.setDirrecion(nuevaDireccion);
        }
    }

    private void editarTelefono(Empleado empleado) {
        String nuevoTelefono = JOptionPane.showInputDialog("Ingrese el nuevo telefono del empleado (o presione OK si no quiere cambiarlo)");
        if (!nuevoTelefono.isEmpty()) {
            empleado.setTelefono(nuevoTelefono);
        }
    }

    private void editarEmail(Empleado empleado) {
        String nuevoEmail = JOptionPane.showInputDialog("Ingrese el nuevo correo electronico del empleado (o presione OK si no quiere cambiarlo)");
        if (!nuevoEmail.isEmpty()) {
            empleado.setEmail(nuevoEmail);
        }
    }

    private void editarEstado(Empleado empleado) {
        int opcion = JOptionPane.showConfirmDialog(null, "Quiere cambiar el estado del empleado?", "Edit Employee Status", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            empleado.setEstado(!empleado.isEstado());
        }

    }//GEN-LAST:event_editarEmpleadoActionPerformed

    private void limpiarEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarEspaciosActionPerformed
        nombre.setText(null);
        apellidosEmpleado.setText(null);
        cuidadEmpleado.setText(null);
        direccionEmpleado.setText(null);
        telefonoEmpleado.setText(null);
        emailEmpleado.setText(null);
    }//GEN-LAST:event_limpiarEspaciosActionPerformed

    private void cargarDesdeArchivo() {
    listaEmpleados.clear();
    try (BufferedReader archivo = new BufferedReader(new FileReader("src/main/java/BaseDeDatos/Empleados.txt"))) {
        String line;
        while ((line = archivo.readLine()) != null) {
            Empleado empleado = partesEmpleado(line);
            if (empleado != null) {
                listaEmpleados.add(empleado);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private Empleado partesEmpleado(String line) {
    String[] partes = line.split("\\s+");
    if (partes.length >= 7) {
        Empleado empleado = new Empleado();
        empleado.setNombre(partes[0]);
        empleado.setApellidos(partes[1]);
        empleado.setCuidad(partes[2]);
        empleado.setDirrecion(partes[3]);
        empleado.setTelefono(partes[4]);
        empleado.setEmail(partes[5]);
        empleado.setEstado(Boolean.parseBoolean(partes[6]));
        return empleado;
    } else {
        return null;
    }
}

    private void guardarEnArchivo() {
    try (BufferedWriter archivo = new BufferedWriter(new FileWriter("src/main/java/BaseDeDatos/Empleados.txt"))) {
        for (Empleado emp : listaEmpleados) {
            archivo.write(formatoEmpleado(emp));
            archivo.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar en el archivo: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
    }
}
    private void limpiar(){
        nombre.setText(null);
        apellidosEmpleado.setText(null);
        cuidadEmpleado.setText(null);
        direccionEmpleado.setText(null);
        telefonoEmpleado.setText(null);
        emailEmpleado.setText(null);
    }
    private void mostrarEmpleadoEspecifico(Empleado empleado) {
    JOptionPane.showMessageDialog(
            null,
            "Nombre: " + empleado.getNombre() + "\n" +
            "Apellidos: " + empleado.getApellidos() + "\n" +
            "Cuidad: " + empleado.getCuidad() + "\n" +
            "Dirección: " + empleado.getDirrecion() + "\n" +
            "Teléfono: " + empleado.getTelefono() + "\n" +
            "Correo Electrónico: " + empleado.getEmail() + "\n" +
            "Estado: " + (empleado.isEstado() ? "Activo" : "Inactivo"),
            "Detalles del Empleado",
            JOptionPane.INFORMATION_MESSAGE
    );
    
}
    private Empleado encontrarEmpleado(String nombre, String email) {
       for (Empleado empleado : listaEmpleados) {
           if (empleado.getNombre().equals(nombre) && empleado.getEmail().equals(email)) {
               return empleado;
           }
       }
       return null;
   }
    
    private String formatoEmpleado(Empleado emp) {
    return String.format("%s %s %s %s %s %s %s",
            emp.getNombre(), emp.getApellidos(), emp.getCuidad(), emp.getDirrecion(), emp.getTelefono(), emp.getEmail(), emp.isEstado());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosEmpleado;
    private javax.swing.JTextField cuidadEmpleado;
    private javax.swing.JTextField direccionEmpleado;
    private javax.swing.JButton editarEmpleado;
    private javax.swing.JTextField emailEmpleado;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCuidad;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmaill;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTelefono1;
    private javax.swing.JLabel labelTelefono3;
    private javax.swing.JLabel labelTelefono4;
    private javax.swing.JLabel labelTelefono5;
    private javax.swing.JButton limpiarEspacios;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton registrarEmpleado;
    private javax.swing.JTextField telefonoEmpleado;
    private javax.swing.JButton volverACatalogo;
    // End of variables declaration//GEN-END:variables
}
