/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe.Administrador.Empleados;

import Catalogos.Personal.Empleado;
import Jframe.Administrador.Catalogos;
import java.util.ArrayList;

/**
 *
 * @author manri
 */
public class EditarEmpleados extends javax.swing.JFrame {
    private ArrayList<Empleado> listaEmpleados;
    /**
     * Creates new form EditarEmpleados
     */
    Empleado empleado = new Empleado();
    public EditarEmpleados() {
        initComponents();
    }
    
    public void setListaEmpleados(ArrayList<Empleado> listaEmpleados) {
        this.listaEmpleados = listaEmpleados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarNombre = new javax.swing.JButton();
        editarApellidos = new javax.swing.JButton();
        editarDireccion = new javax.swing.JButton();
        editarCuidad = new javax.swing.JButton();
        editarEmail = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        editarTelefono = new javax.swing.JButton();
        labelApellidos = new javax.swing.JLabel();
        labelCuidad = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelEmaill = new javax.swing.JLabel();
        volverACatalogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editarNombre.setText("Editar");
        editarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarNombreActionPerformed(evt);
            }
        });

        editarApellidos.setText("Editar");
        editarApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarApellidosActionPerformed(evt);
            }
        });

        editarDireccion.setText("Editar");
        editarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDireccionActionPerformed(evt);
            }
        });

        editarCuidad.setText("Editar");
        editarCuidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCuidadActionPerformed(evt);
            }
        });

        editarEmail.setText("Editar");
        editarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmailActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre");

        editarTelefono.setText("Editar");
        editarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTelefonoActionPerformed(evt);
            }
        });

        labelApellidos.setText("Apellidos");

        labelCuidad.setText("Cuidad");

        labelDireccion.setText("Dirección");

        labelTelefono.setText("Teléfono");

        labelEmaill.setText("Correo Electronico");

        volverACatalogo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        volverACatalogo.setText("Volver a Catalogo");
        volverACatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverACatalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelCuidad)
                            .addComponent(labelTelefono)
                            .addComponent(editarNombre)
                            .addComponent(editarCuidad)
                            .addComponent(editarTelefono))
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelApellidos)
                            .addComponent(labelDireccion)
                            .addComponent(editarEmail)
                            .addComponent(editarDireccion)
                            .addComponent(editarApellidos)
                            .addComponent(labelEmaill)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(volverACatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarNombre)
                    .addComponent(editarApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuidad)
                    .addComponent(labelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarDireccion)
                    .addComponent(editarCuidad))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(labelEmaill))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarEmail)
                    .addComponent(editarTelefono))
                .addGap(52, 52, 52)
                .addComponent(volverACatalogo)
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarNombreActionPerformed
        empleado.setNumeroEditar(1);
        empleado.editarEmpleado();
    }//GEN-LAST:event_editarNombreActionPerformed

    private void editarApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarApellidosActionPerformed
        empleado.setNumeroEditar(2);
        empleado.editarEmpleado();
    }//GEN-LAST:event_editarApellidosActionPerformed

    private void editarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDireccionActionPerformed
        empleado.setNumeroEditar(4);
        empleado.editarEmpleado();
    }//GEN-LAST:event_editarDireccionActionPerformed

    private void editarCuidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCuidadActionPerformed
        empleado.setNumeroEditar(3);
        empleado.editarEmpleado();
    }//GEN-LAST:event_editarCuidadActionPerformed

    private void editarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmailActionPerformed
        empleado.setNumeroEditar(6);
        empleado.editarEmpleado();
    }//GEN-LAST:event_editarEmailActionPerformed

    private void editarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTelefonoActionPerformed
        empleado.setNumeroEditar(5);
        empleado.editarEmpleado();
    }//GEN-LAST:event_editarTelefonoActionPerformed

    private void volverACatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverACatalogoActionPerformed
        Catalogos catalogos = new Catalogos();
        catalogos.setVisible(true);
        catalogos.pack();
        catalogos.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volverACatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarApellidos;
    private javax.swing.JButton editarCuidad;
    private javax.swing.JButton editarDireccion;
    private javax.swing.JButton editarEmail;
    private javax.swing.JButton editarNombre;
    private javax.swing.JButton editarTelefono;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCuidad;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmaill;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JButton volverACatalogo;
    // End of variables declaration//GEN-END:variables
}
