/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe.Administrador;

import Catalogos.Personal.Empleado;
import Jframe.Administrador.Atracciones.AgregarAtracciones;
import Jframe.Administrador.Atracciones.EditarAtracciones;
import Jframe.Administrador.Atracciones.InactivarAtracciones;
import Jframe.Administrador.CategoriaAtraccion.AgregarCategoriasAtraccion;
import Jframe.Administrador.CategoriaAtraccion.EditarCategoriasAtraccion;
import Jframe.Administrador.CategoriaAtraccion.InactivarCategoriasAtraccion;
import Jframe.Administrador.Empleados.AgregarEmpleados;
import Jframe.Administrador.Empleados.EditarEmpleados;
import Jframe.Administrador.Empleados.InactivarEmpleados;
import java.util.ArrayList;

/**
 *
 * @author manri
 */
public class Catalogos extends javax.swing.JFrame {
    private ArrayList<Empleado> listaEmpleados;
    /**
     * Creates new form Catalogos
     */
    public Catalogos() {
        initComponents();
        
    }
    
    public void setListaEmpleados(ArrayList<Empleado> listaEmpleados) {
        this.listaEmpleados = listaEmpleados;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregarEmpleados = new javax.swing.JButton();
        editarEmpleados = new javax.swing.JButton();
        inactivarEmpleados = new javax.swing.JButton();
        agregarCategoriaAtraccion = new javax.swing.JButton();
        editarCategoriaAtraccion = new javax.swing.JButton();
        inactivarCategoriaAtraccion = new javax.swing.JButton();
        agregarAtracciones = new javax.swing.JButton();
        editarAtracciones = new javax.swing.JButton();
        inactivarAtracciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Catalogos");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Empleados");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Atracciones");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Categoria Atraccion");

        agregarEmpleados.setText("Agregar");
        agregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadosActionPerformed(evt);
            }
        });

        editarEmpleados.setText("Editar");
        editarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadosActionPerformed(evt);
            }
        });

        inactivarEmpleados.setText("Inactivar");
        inactivarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactivarEmpleadosActionPerformed(evt);
            }
        });

        agregarCategoriaAtraccion.setText("Agregar");
        agregarCategoriaAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCategoriaAtraccionActionPerformed(evt);
            }
        });

        editarCategoriaAtraccion.setText("Editar");
        editarCategoriaAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCategoriaAtraccionActionPerformed(evt);
            }
        });

        inactivarCategoriaAtraccion.setText("Inactivar");
        inactivarCategoriaAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactivarCategoriaAtraccionActionPerformed(evt);
            }
        });

        agregarAtracciones.setText("Agregar");
        agregarAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAtraccionesActionPerformed(evt);
            }
        });

        editarAtracciones.setText("Editar");
        editarAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAtraccionesActionPerformed(evt);
            }
        });

        inactivarAtracciones.setText("Inactivar");
        inactivarAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactivarAtraccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inactivarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarCategoriaAtraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarCategoriaAtraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inactivarCategoriaAtraccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarAtracciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarAtracciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inactivarAtracciones))
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 154, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel3)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(342, 342, 342))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarAtracciones)
                        .addGap(33, 33, 33)
                        .addComponent(editarAtracciones)
                        .addGap(36, 36, 36)
                        .addComponent(inactivarAtracciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarEmpleados)
                                .addGap(33, 33, 33)
                                .addComponent(editarEmpleados)
                                .addGap(36, 36, 36)
                                .addComponent(inactivarEmpleados))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(agregarCategoriaAtraccion)
                                .addGap(33, 33, 33)
                                .addComponent(editarCategoriaAtraccion)
                                .addGap(36, 36, 36)
                                .addComponent(inactivarCategoriaAtraccion)))))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadosActionPerformed
        AgregarEmpleados empleados = new AgregarEmpleados();
        empleados.setVisible(true);
        empleados.pack();
        empleados.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_agregarEmpleadosActionPerformed

    private void editarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadosActionPerformed
        EditarEmpleados empleados = new EditarEmpleados();
        empleados.setVisible(true);
        empleados.pack();
        empleados.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_editarEmpleadosActionPerformed

    private void inactivarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactivarEmpleadosActionPerformed
        InactivarEmpleados empleados = new InactivarEmpleados();
        empleados.setVisible(true);
        empleados.pack();
        empleados.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_inactivarEmpleadosActionPerformed

    private void agregarCategoriaAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCategoriaAtraccionActionPerformed
        AgregarCategoriasAtraccion categorias = new AgregarCategoriasAtraccion();
        categorias.setVisible(true);
        categorias.pack();
        categorias.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_agregarCategoriaAtraccionActionPerformed

    private void editarCategoriaAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCategoriaAtraccionActionPerformed
        EditarCategoriasAtraccion categorias = new EditarCategoriasAtraccion();
        categorias.setVisible(true);
        categorias.pack();
        categorias.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_editarCategoriaAtraccionActionPerformed

    private void inactivarCategoriaAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactivarCategoriaAtraccionActionPerformed
        InactivarCategoriasAtraccion categorias = new InactivarCategoriasAtraccion();
        categorias.setVisible(true);
        categorias.pack();
        categorias.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_inactivarCategoriaAtraccionActionPerformed

    private void agregarAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAtraccionesActionPerformed
        AgregarAtracciones atracciones = new AgregarAtracciones();
        atracciones.setVisible(true);
        atracciones.pack();
        atracciones.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_agregarAtraccionesActionPerformed

    private void editarAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAtraccionesActionPerformed
        EditarAtracciones atracciones = new EditarAtracciones();
        atracciones.setVisible(true);
        atracciones.pack();
        atracciones.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_editarAtraccionesActionPerformed

    private void inactivarAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactivarAtraccionesActionPerformed
        InactivarAtracciones atracciones = new InactivarAtracciones();
        atracciones.setVisible(true);
        atracciones.pack();
        atracciones.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_inactivarAtraccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAtracciones;
    private javax.swing.JButton agregarCategoriaAtraccion;
    private javax.swing.JButton agregarEmpleados;
    private javax.swing.JButton editarAtracciones;
    private javax.swing.JButton editarCategoriaAtraccion;
    private javax.swing.JButton editarEmpleados;
    private javax.swing.JButton inactivarAtracciones;
    private javax.swing.JButton inactivarCategoriaAtraccion;
    private javax.swing.JButton inactivarEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
