/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe.Administrador;

import Jframe.Administrador.Atracciones.CatalogoAtracciones;
import Jframe.Administrador.CategoriaAtraccion.CatalogoCategoriasDeAtracciones;
import Jframe.Administrador.Empleados.CatalogoEmpleado;
import Jframe.Administrador.Ingresos.IngresosDiarios;
import Jframe.IniciodeSesionYRegistro.InicioDeSesion;

/**
 *
 * @author manri
 */
public class Catalogos extends javax.swing.JFrame {
    /**
     * Creates new form Catalogos
     */
    public Catalogos() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarEmpleados = new javax.swing.JButton();
        agregarCategoriaAtraccion = new javax.swing.JButton();
        agregarAtracciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        agregarEmpleados.setFont(agregarEmpleados.getFont().deriveFont(agregarEmpleados.getFont().getStyle() | java.awt.Font.BOLD, agregarEmpleados.getFont().getSize()+11));
        agregarEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        agregarEmpleados.setText("Empleados");
        agregarEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        agregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(agregarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 80));

        agregarCategoriaAtraccion.setBackground(new java.awt.Color(255, 255, 255));
        agregarCategoriaAtraccion.setFont(agregarCategoriaAtraccion.getFont().deriveFont(agregarCategoriaAtraccion.getFont().getStyle() | java.awt.Font.BOLD, agregarCategoriaAtraccion.getFont().getSize()+11));
        agregarCategoriaAtraccion.setForeground(new java.awt.Color(0, 0, 0));
        agregarCategoriaAtraccion.setText("Categoria Atraccion");
        agregarCategoriaAtraccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        agregarCategoriaAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCategoriaAtraccionActionPerformed(evt);
            }
        });
        getContentPane().add(agregarCategoriaAtraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 270, 80));

        agregarAtracciones.setBackground(new java.awt.Color(255, 255, 255));
        agregarAtracciones.setFont(agregarAtracciones.getFont().deriveFont(agregarAtracciones.getFont().getStyle() | java.awt.Font.BOLD, agregarAtracciones.getFont().getSize()+11));
        agregarAtracciones.setForeground(new java.awt.Color(0, 0, 0));
        agregarAtracciones.setText("Atracciones");
        agregarAtracciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        agregarAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAtraccionesActionPerformed(evt);
            }
        });
        getContentPane().add(agregarAtracciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 190, 80));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getSize()+5f));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver a Pantalla de Usuarios");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 300, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getStyle() | java.awt.Font.BOLD, jButton2.getFont().getSize()+11));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Ingresos Diarios");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 270, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catalofoAdministrador.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadosActionPerformed
        CatalogoEmpleado empleados = new CatalogoEmpleado();
        empleados.setVisible(true);
        empleados.pack();
        empleados.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_agregarEmpleadosActionPerformed

    private void agregarCategoriaAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCategoriaAtraccionActionPerformed
        CatalogoCategoriasDeAtracciones categorias = new CatalogoCategoriasDeAtracciones();
        categorias.setVisible(true);
        categorias.pack();
        categorias.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_agregarCategoriaAtraccionActionPerformed

    private void agregarAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAtraccionesActionPerformed
        CatalogoAtracciones atracciones = new CatalogoAtracciones();
        atracciones.setVisible(true);
        atracciones.pack();
        atracciones.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_agregarAtraccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       InicioDeSesion atracciones = new InicioDeSesion();
        atracciones.setVisible(true);
        atracciones.pack();
        atracciones.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        IngresosDiarios atracciones = new IngresosDiarios();
        atracciones.setVisible(true);
        atracciones.pack();
        atracciones.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAtracciones;
    private javax.swing.JButton agregarCategoriaAtraccion;
    private javax.swing.JButton agregarEmpleados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
